In [34]:
# Imports
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

In [35]:
# Import data
filename = 'OMA-project-data.csv'
df = pd.read_csv(filename, dtype={'IMG_': str})

#add decade col
def create_decade(x):
    d = str(x['YEAR'])
    e = d[:3] + "0s"
    return e

df['DECADE'] = df.apply(create_decade, axis=1)

#Update image column with paths to B/W photos
bw_path = "D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Black and White Images\\"

def create_bw_path(x):
    return bw_path + str(x['IMG_']) + ".jpg"
    
df['@IMG'] = df.apply(create_bw_path, axis=1)

#Update image column with paths to Typology backgrounds
type_path = "D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Typology Backgrounds\\"

def create_type_path(x):
    return type_path + str(x['TYPOLOGY_01']) + ".png"
    
df['@TYPE_BG'] = df.apply(create_type_path, axis=1)

#Drop
df = df.drop(["LINK", "TYPOLOGY_02", "URL STRING", "Unnamed: 11", "IMG_", "@Photos"], axis=1)

# Organise columns
df["TEAM LIST"] = np.nan

cols = df.columns.tolist()
cols = cols[-4:] + cols[:-4]
df = df[cols]

df.head(2)

,DECADE,@IMG,@TYPE_BG,TEAM LIST,DESCRIPTION,YEAR,TYPE,STATUS,TYPOLOGY_01,REM?,...,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109
0,1970s,D:\Google Drive\Architecture\2017\11222 Critiq...,D:\Google Drive\Architecture\2017\11222 Critiq...,NaN,Delirious New York,1978,Publication,Publication,NaN,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1970s,D:\Google Drive\Architecture\2017\11222 Critiq...,D:\Google Drive\Architecture\2017\11222 Critiq...,NaN,Dutch Parliament Extension,1978,Project,Competition,Office,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
# status_dict = {
#                "Commissioned Study": 1,
#                "Competition": 2,
#                "Completed": 4,
#                "Construction": 2,
#                "Demolished": 2,
#                "Design Development": 2,
#                "Lecture": 0,
#                "Publication": 4,
#                "Study": 0
#                }

# typology_dict = {
#                  "N/A": 0,
#                  "Arena": 0,
#                  "Branding": 1,
#                  "Education": 2,
#                  "Exhibition": 2,
#                  "Hotel": 2,
#                  "Industrial": 0,
#                  "Infrastructure": 0,
#                  "Landscape": 2,
#                  "Library": 3,
#                  "Masterplan": 3,
#                  "Mixed use": 4,
#                  "Museum / Gallery": 3,
#                  "Office": 0,
#                  "Product Design": 0,
#                  "Research": 0,
#                  "Residential": 1,
#                  "Restaurant / Bar": 0,
#                  "Retail": 2,
#                  "Scenography": 3,
#                  "Theatre": 3,
#                  "Tower": 0
#                  }

# decades_dict = {
#                 "1970s": 5,
#                 "1980s": 3,
#                 "1990s": 1,
#                 "2000s": 0
#                 }


# dict_dict = {
#             "STATUS": status_dict,
#             "TYPOLOGY_01": typology_dict,
#             "DECADE": decades_dict
#             }

In [37]:
# def set_value (dictionary, key):
#     max_dict = max([i for i in dictionary.values()])
#     x = dictionary[key] / max_dict
#     return x

# def importance_factor(y):
#     z = []
    
#     for k in dict_dict:
#         try:
#             m = dict_dict[k]
#             n = y[k]
#             z.append(set_value(m, n))
#         except:
#             pass
    
#     a = float(len(z))
#     b = float(sum(z))
#     return (b/a)

In [38]:
# df['IMPORTANCE'] = df.apply(importance_factor, axis=1)

# df.sort_values("IMPORTANCE", ascending=False).head(1)

In [39]:
#Create team list
team_cols = df.loc[:, 'TEAM_01':].columns.tolist()
team_cols_len = len(team_cols)

def create_team(x):
    y = []
    for i in team_cols:
        y.append(x[i])
    return y

df["TEAM LIST"] = df.apply(create_team, axis=1)

df.head(2)

,DECADE,@IMG,@TYPE_BG,TEAM LIST,DESCRIPTION,YEAR,TYPE,STATUS,TYPOLOGY_01,REM?,...,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109
0,1970s,D:\Google Drive\Architecture\2017\11222 Critiq...,D:\Google Drive\Architecture\2017\11222 Critiq...,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",Delirious New York,1978,Publication,Publication,NaN,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1970s,D:\Google Drive\Architecture\2017\11222 Critiq...,D:\Google Drive\Architecture\2017\11222 Critiq...,"[Zaha Hadid, Richard Perlemutter, Ron Steiner,...",Dutch Parliament Extension,1978,Project,Competition,Office,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
team_list = df["TEAM LIST"].tolist()

def find_names(name):
    j = []

    for i in team_list:
        j.append(name in i)
    return j

def name_frame(name):
    p = find_names(name)
    q = df[p]
    return q

In [41]:
# Load primary name list
a = ""
b = ""
c = ""

a = 'project-people.txt'
b = open(a)
c = b.readlines()

primary_list = []

for i in c:
    y = i.strip()
    primary_list.append(y)
    
# Load secondary name list
a = ""
b = ""
c = ""

a = 'generations-people.txt'
b = open(a)
c = b.readlines()

secondary_list = []

for i in c:
    y = i.strip()
    secondary_list.append(y)

print primary_list
print secondary_list

['Jeroen Thomas', 'Ron Steiner', 'Chris van Duijn', 'Frans Blok', 'Shohei Shigematsu', 'Reinier de Graaf', 'Xaveer de Geyter', 'Floris Alkemade', 'Fernando Donis', 'Dan Wood']
['Christian Rapp', 'Edzo Bindels', 'Christophe Cornubert', 'Matthias Sauerbruch', 'Kees Christiaanse', 'Yushi Uehara', 'Zaha Hadid', 'Laurinda Spear', 'Ruurd Roorda', 'Williem Jan Neutelings', 'Winy Maas', 'Jacob Van Rijs', 'Sarah Whiting', 'Ron Witte', 'Mike Guyer', 'Alejandro Zaera Polo', 'Luc Reuse', 'Farshid Moussavi', 'Rients Dijkstra', 'Jeffery Inaba', 'Amale Andraos', 'Juliette Bekkering', 'John Mcmorrough', 'Matthias Hollwich', 'Jeanne Gang', 'Fernando Romero', 'Markus Schaefer', 'Zachary R.Heineman', 'Joshua Prince-Ramus', 'Erez Ella', 'Bjarke Ingels', 'Julien De Smedt', 'Patrick Louwere', 'Bart Eijking', 'Ole Scheeren', 'Eric Chang']

In [52]:
def process_names(d):
    f = name_frame(d)
    f = f.drop(f.loc[:, 'TEAM_01':], axis=1)
    h = len(f["YEAR"].tolist())
    f["BRANCH KEY"] = d
    f["KEY TOTAL"] = h
    print "Done: " + d
    return f

count = 0
index = []
columns = []
total_df = pd.DataFrame(index=index, columns=columns)

for g in primary_list:
    total_df = total_df.append(process_names(g))
    count += 1

total_df.head()
# save_path = "people_output/_total-people.csv"
# total_df.to_csv(save_path, index=False)
# print "Processed: " + str(count)

Done: Jeroen Thomas
Done: Ron Steiner
Done: Chris van Duijn
Done: Frans Blok
Done: Shohei Shigematsu
Done: Reinier de Graaf
Done: Xaveer de Geyter
Done: Floris Alkemade
Done: Fernando Donis
Done: Dan Wood

,DECADE,@IMG,@TYPE_BG,TEAM LIST,DESCRIPTION,YEAR,TYPE,STATUS,TYPOLOGY_01,REM?,BRANCH KEY,KEY TOTAL
3,1980s,D:\Google Drive\Architecture\2017\11222 Critiq...,D:\Google Drive\Architecture\2017\11222 Critiq...,"[Kees Christiaanse, Gerard Comello, Stefano de...",Boompjes,1980,Project,Commissioned Study,Residential,True,Jeroen Thomas,29
9,1980s,D:\Google Drive\Architecture\2017\11222 Critiq...,D:\Google Drive\Architecture\2017\11222 Critiq...,"[Kees Christiaanse, Jaap van Heest, GÃ¶tz Kelle...",Churchillplein,1984,Project,Competition,Office,True,Jeroen Thomas,29
14,1980s,D:\Google Drive\Architecture\2017\11222 Critiq...,D:\Google Drive\Architecture\2017\11222 Critiq...,"[Arjan Karssenberg, Jeroen Thomas, nan, nan, n...",Police Station,1985,Project,Completed,Office,True,Jeroen Thomas,29
15,1980s,D:\Google Drive\Architecture\2017\11222 Critiq...,D:\Google Drive\Architecture\2017\11222 Critiq...,"[Kees Christiaanse, Jeroen Thomas, nan, nan, n...",Torenstraat,1985,Project,Commissioned Study,Masterplan,True,Jeroen Thomas,29
18,1980s,D:\Google Drive\Architecture\2017\11222 Critiq...,D:\Google Drive\Architecture\2017\11222 Critiq...,"[Herman Helle, GÃ¶tz Keller, Brigitte Kochta, M...",City Hall The Hague,1986,Project,Competition,Office,True,Jeroen Thomas,29