In [60]:
# Imports
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import csv

In [61]:
# Import data
filename = 'OMA-project-data.csv'
df = pd.read_csv(filename, dtype={'IMG_': str})

#add decade col
def create_decade(x):
    d = str(x['YEAR'])
    e = d[:3] + "0s"
    return e

df['DECADE'] = df.apply(create_decade, axis=1)

#Update image column with paths to B/W photos
bw_path = "D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Black and White Images\\"

def create_bw_path(x):
    return bw_path + str(x['IMG_']) + ".jpg"
    
df['@IMG'] = df.apply(create_bw_path, axis=1)

#Update image column with paths to Typology backgrounds
type_path = "D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Typology Backgrounds\\"

def create_type_path(x):
    return type_path + str(x['TYPOLOGY_01']) + ".png"
    
df['@TYPE_BG'] = df.apply(create_type_path, axis=1)

#Drop
df = df.drop(["LINK", "TYPOLOGY_02", "URL STRING", "Unnamed: 11", "IMG_", "@Photos"], axis=1)

# Organise columns
df["TEAM LIST"] = np.nan

cols = df.columns.tolist()
cols = cols[-4:] + cols[:-4]
df = df[cols]

df.head(2)

,DECADE,@IMG,@TYPE_BG,TEAM LIST,DESCRIPTION,YEAR,TYPE,STATUS,TYPOLOGY_01,REM?,...,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109
0,1970s,D:\Google Drive\Architecture\2017\11222 Critiq...,D:\Google Drive\Architecture\2017\11222 Critiq...,NaN,Delirious New York,1978,Publication,Publication,NaN,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1970s,D:\Google Drive\Architecture\2017\11222 Critiq...,D:\Google Drive\Architecture\2017\11222 Critiq...,NaN,Dutch Parliament Extension,1978,Project,Competition,Office,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
# status_dict = {
#                "Commissioned Study": 1,
#                "Competition": 2,
#                "Completed": 4,
#                "Construction": 2,
#                "Demolished": 2,
#                "Design Development": 2,
#                "Lecture": 0,
#                "Publication": 4,
#                "Study": 0
#                }

# typology_dict = {
#                  "N/A": 0,
#                  "Arena": 0,
#                  "Branding": 1,
#                  "Education": 2,
#                  "Exhibition": 2,
#                  "Hotel": 2,
#                  "Industrial": 0,
#                  "Infrastructure": 0,
#                  "Landscape": 2,
#                  "Library": 3,
#                  "Masterplan": 3,
#                  "Mixed use": 4,
#                  "Museum / Gallery": 3,
#                  "Office": 0,
#                  "Product Design": 0,
#                  "Research": 0,
#                  "Residential": 1,
#                  "Restaurant / Bar": 0,
#                  "Retail": 2,
#                  "Scenography": 3,
#                  "Theatre": 3,
#                  "Tower": 0
#                  }

# decades_dict = {
#                 "1970s": 5,
#                 "1980s": 3,
#                 "1990s": 1,
#                 "2000s": 0
#                 }


# dict_dict = {
#             "STATUS": status_dict,
#             "TYPOLOGY_01": typology_dict,
#             "DECADE": decades_dict
#             }

In [63]:
# def set_value (dictionary, key):
#     max_dict = max([i for i in dictionary.values()])
#     x = dictionary[key] / max_dict
#     return x

# def importance_factor(y):
#     z = []
    
#     for k in dict_dict:
#         try:
#             m = dict_dict[k]
#             n = y[k]
#             z.append(set_value(m, n))
#         except:
#             pass
    
#     a = float(len(z))
#     b = float(sum(z))
#     return (b/a)

In [64]:
# df['IMPORTANCE'] = df.apply(importance_factor, axis=1)

# df.sort_values("IMPORTANCE", ascending=False).head(1)

In [65]:
#Create team list
team_cols = df.loc[:, 'TEAM_01':].columns.tolist()
team_cols_len = len(team_cols)

def create_team(x):
    y = []
    for i in team_cols:
        y.append(x[i])
    return y

df["TEAM LIST"] = df.apply(create_team, axis=1)

df.head(2)

,DECADE,@IMG,@TYPE_BG,TEAM LIST,DESCRIPTION,YEAR,TYPE,STATUS,TYPOLOGY_01,REM?,...,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109
0,1970s,D:\Google Drive\Architecture\2017\11222 Critiq...,D:\Google Drive\Architecture\2017\11222 Critiq...,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",Delirious New York,1978,Publication,Publication,NaN,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1970s,D:\Google Drive\Architecture\2017\11222 Critiq...,D:\Google Drive\Architecture\2017\11222 Critiq...,"[Zaha Hadid, Richard Perlemutter, Ron Steiner,...",Dutch Parliament Extension,1978,Project,Competition,Office,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
team_list = df["TEAM LIST"].tolist()

def find_names(name):
    j = []

    for i in team_list:
        j.append(name in i)
    return j

def name_frame(name):
    p = find_names(name)
    q = df[p]
    return q

In [67]:
#Set up for paths to Gender backgrounds
gender_img_path = "D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\"

def create_gender_path(o):
    n = gender_img_path + str(o['GENDER']) + ".png"
    return n

In [68]:
# Load primary name list
a = ""

a = 'project-people.csv'
primary_df = pd.read_csv(a)

primary_list = primary_df["NAME"].tolist()
print primary_list

primary_df["@Gender"] = primary_df.apply(create_gender_path, axis=1)

save_primary_path = "total_output/primary-people_names.csv"
primary_df.to_csv(save_primary_path, index=False, encoding='utf-8')
print "Saved: " + save_primary_path

primary_df.head()

['Jeroen Thomas', 'Ron Steiner', 'Chris van Duijn', 'Frans Blok', 'Shohei Shigematsu', 'Reinier de Graaf', 'Xaveer de Geyter', 'Floris Alkemade', 'Fernando Donis', 'Dan Wood']
Saved: total_output/primary-people_names.csv

                NAME GENDER                                            @Gender
0      Jeroen Thomas   Male  D:\Google Drive\Architecture\2017\11222 Critiq...
1        Ron Steiner   Male  D:\Google Drive\Architecture\2017\11222 Critiq...
2    Chris van Duijn   Male  D:\Google Drive\Architecture\2017\11222 Critiq...
3         Frans Blok   Male  D:\Google Drive\Architecture\2017\11222 Critiq...
4  Shohei Shigematsu   Male  D:\Google Drive\Architecture\2017\11222 Critiq...

In [69]:
# # Load secondary name list
a = ""

a = 'generations-people.csv'
secondary_df = pd.read_csv(a)

secondary_df["@Gender"] = secondary_df.apply(create_gender_path, axis=1)

secondary_list = secondary_df["NAME"].tolist()
secondary_genders_img = secondary_df["@Gender"].tolist()
print secondary_list
print secondary_genders_img
secondary_df.head()

['Christian Rapp', 'Edzo Bindels', 'Christophe Cornubert', 'Matthias Sauerbruch', 'Kees Christiaanse', 'Yushi Uehara', 'Zaha Hadid', 'Laurinda Spear', 'Ruurd Roorda', 'Williem Jan Neutelings', 'Winy Maas', 'Jacob Van Rijs', 'Sarah Whiting', 'Ron Witte', 'Mike Guyer', 'Alejandro Zaera Polo', 'Luc Reuse', 'Farshid Moussavi', 'Rients Dijkstra', 'Jeffery Inaba', 'Amale Andraos', 'JulietteBekkering', 'John Mcmorrough', 'Matthias Hollwich', 'Jeanne Gang', 'Fernando Romero', 'Markus Schaefer', 'Zachary R.Heineman', 'Joshua Prince-Ramus', 'Erez Ella', 'Bjarke Ingels', 'Julien De Smedt', 'Patrick Louwere', 'Bart Eijking', 'Ole Scheeren', 'Eric Chang']
['D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Male.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Male.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Male.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Male.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Male.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Male.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Female.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Female.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Male.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Male.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Male.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Male.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Female.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Male.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Male.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Male.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Male.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Female.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Male.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Male.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Female.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\nan.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Male.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Male.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Female.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Male.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Male.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Male.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Male.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Male.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Male.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Male.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Male.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Male.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Male.png', 'D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Gender Backgrounds\\Male.png']

,NAME,GENDER,@Gender
0,Christian Rapp,Male,D:\Google Drive\Architecture\2017\11222 Critiq...
1,Edzo Bindels,Male,D:\Google Drive\Architecture\2017\11222 Critiq...
2,Christophe Cornubert,Male,D:\Google Drive\Architecture\2017\11222 Critiq...
3,Matthias Sauerbruch,Male,D:\Google Drive\Architecture\2017\11222 Critiq...
4,Kees Christiaanse,Male,D:\Google Drive\Architecture\2017\11222 Critiq...

In [70]:
# Process primary list
def process_names(d):
    f = name_frame(d)
    f = f.drop(f.loc[:, 'TEAM_01':], axis=1)
    h = len(f["YEAR"].tolist())
    f["BRANCH KEY"] = d
    f["KEY TOTAL"] = h
    f.sort_values("YEAR")
    print "Done: " + d
    return f

index = []
columns = []
total_df = pd.DataFrame(index=index, columns=columns)

for g in primary_list:
    total_df = total_df.append(process_names(g))  

total_df.head()

Done: Jeroen Thomas
Done: Ron Steiner
Done: Chris van Duijn
Done: Frans Blok
Done: Shohei Shigematsu
Done: Reinier de Graaf
Done: Xaveer de Geyter
Done: Floris Alkemade
Done: Fernando Donis
Done: Dan Wood

,DECADE,@IMG,@TYPE_BG,TEAM LIST,DESCRIPTION,YEAR,TYPE,STATUS,TYPOLOGY_01,REM?,BRANCH KEY,KEY TOTAL
3,1980s,D:\Google Drive\Architecture\2017\11222 Critiq...,D:\Google Drive\Architecture\2017\11222 Critiq...,"[Kees Christiaanse, Gerard Comello, Stefano de...",Boompjes,1980,Project,Commissioned Study,Residential,True,Jeroen Thomas,29
9,1980s,D:\Google Drive\Architecture\2017\11222 Critiq...,D:\Google Drive\Architecture\2017\11222 Critiq...,"[Kees Christiaanse, Jaap van Heest, GÃ¶tz Kelle...",Churchillplein,1984,Project,Competition,Office,True,Jeroen Thomas,29
14,1980s,D:\Google Drive\Architecture\2017\11222 Critiq...,D:\Google Drive\Architecture\2017\11222 Critiq...,"[Arjan Karssenberg, Jeroen Thomas, nan, nan, n...",Police Station,1985,Project,Completed,Office,True,Jeroen Thomas,29
15,1980s,D:\Google Drive\Architecture\2017\11222 Critiq...,D:\Google Drive\Architecture\2017\11222 Critiq...,"[Kees Christiaanse, Jeroen Thomas, nan, nan, n...",Torenstraat,1985,Project,Commissioned Study,Masterplan,True,Jeroen Thomas,29
18,1980s,D:\Google Drive\Architecture\2017\11222 Critiq...,D:\Google Drive\Architecture\2017\11222 Critiq...,"[Herman Helle, GÃ¶tz Keller, Brigitte Kochta, M...",City Hall The Hague,1986,Project,Competition,Office,True,Jeroen Thomas,29

In [71]:
# Get Secondary key team
def process_secondary_list(r):
    secondary_team = []

    for name in secondary_list:
        if name in r["TEAM LIST"]:
                secondary_team.append(name)
        else:
            pass
    return secondary_team

def process_secondary_list_genders(r):
    secondary_team_genders_paths = []
    length = len(secondary_list)
    for i in range(0, length):
        if secondary_list[i] in r["TEAM LIST"]:
                secondary_team_genders_paths.append(secondary_genders_img[i])
        else:
            pass
    return secondary_team_genders_paths


total_df["SECONDARY TEAM"] = total_df.apply(process_secondary_list, axis=1)
total_df["SECONDARY TEAM GENDER PATHS"] = total_df.apply(process_secondary_list_genders, axis=1)

total_df.head(2)

,DECADE,@IMG,@TYPE_BG,TEAM LIST,DESCRIPTION,YEAR,TYPE,STATUS,TYPOLOGY_01,REM?,BRANCH KEY,KEY TOTAL,SECONDARY TEAM,SECONDARY TEAM GENDER PATHS
3,1980s,D:\Google Drive\Architecture\2017\11222 Critiq...,D:\Google Drive\Architecture\2017\11222 Critiq...,"[Kees Christiaanse, Gerard Comello, Stefano de...",Boompjes,1980,Project,Commissioned Study,Residential,True,Jeroen Thomas,29,[Kees Christiaanse],[D:\Google Drive\Architecture\2017\11222 Criti...
9,1980s,D:\Google Drive\Architecture\2017\11222 Critiq...,D:\Google Drive\Architecture\2017\11222 Critiq...,"[Kees Christiaanse, Jaap van Heest, GÃ¶tz Kelle...",Churchillplein,1984,Project,Competition,Office,True,Jeroen Thomas,29,[Kees Christiaanse],[D:\Google Drive\Architecture\2017\11222 Criti...

In [72]:
def apply_count(g):
    u = len(g["SECONDARY TEAM"])
    return u

total_df["SECONDARY COUNT"] = total_df.apply(apply_count, axis=1)

total_df.head(2)

,DECADE,@IMG,@TYPE_BG,TEAM LIST,DESCRIPTION,YEAR,TYPE,STATUS,TYPOLOGY_01,REM?,BRANCH KEY,KEY TOTAL,SECONDARY TEAM,SECONDARY TEAM GENDER PATHS,SECONDARY COUNT
3,1980s,D:\Google Drive\Architecture\2017\11222 Critiq...,D:\Google Drive\Architecture\2017\11222 Critiq...,"[Kees Christiaanse, Gerard Comello, Stefano de...",Boompjes,1980,Project,Commissioned Study,Residential,True,Jeroen Thomas,29,[Kees Christiaanse],[D:\Google Drive\Architecture\2017\11222 Criti...,1
9,1980s,D:\Google Drive\Architecture\2017\11222 Critiq...,D:\Google Drive\Architecture\2017\11222 Critiq...,"[Kees Christiaanse, Jaap van Heest, GÃ¶tz Kelle...",Churchillplein,1984,Project,Competition,Office,True,Jeroen Thomas,29,[Kees Christiaanse],[D:\Google Drive\Architecture\2017\11222 Criti...,1

In [73]:
def second_1(f):
    try:
        g = f["SECONDARY TEAM"][0]
        return g
    except:
        return np.nan

    
def second_2(f):
    try:
        g = f["SECONDARY TEAM"][1]
        return g
    except:
        return np.nan
    
def second_3(f):
    try:
        g = f["SECONDARY TEAM"][2]
        return g
    except:
        return np.nan
    
def second_4(f):
    try:
        g = f["SECONDARY TEAM"][3]
        return g
    except:
        return np.nan

def second_5(f):
    try:
        g = f["SECONDARY TEAM"][4]
        return g
    except:
        return np.nan

def second_6(f):
    try:
        g = f["SECONDARY TEAM"][5]
        return g
    except:
        return np.nan

def second_7(f):
    try:
        g = f["SECONDARY TEAM"][6]
        return g
    except:
        return np.nan

def second_8(f):
    try:
        g = f["SECONDARY TEAM"][7]
        return g
    except:
        return np.nan

def second_9(f):
    try:
        g = f["SECONDARY TEAM"][8]
        return g
    except:
        return np.nan
    
def second_10(f):
    try:
        g = f["SECONDARY TEAM"][9]
        return g
    except:
        return np.nan
    

total_df["SECONDARY 01"] = total_df.apply(second_1, axis=1)
total_df["SECONDARY 02"] = total_df.apply(second_2, axis=1)
total_df["SECONDARY 03"] = total_df.apply(second_3, axis=1)
total_df["SECONDARY 04"] = total_df.apply(second_4, axis=1)
total_df["SECONDARY 05"] = total_df.apply(second_5, axis=1)
total_df["SECONDARY 06"] = total_df.apply(second_6, axis=1)
total_df["SECONDARY 07"] = total_df.apply(second_7, axis=1)
total_df["SECONDARY 08"] = total_df.apply(second_8, axis=1)
total_df["SECONDARY 09"] = total_df.apply(second_9, axis=1)
total_df["SECONDARY 10"] = total_df.apply(second_10, axis=1)

In [76]:
def second_gender_1(f):
    try:
        g = f["SECONDARY TEAM GENDER PATHS"][0]
        return g
    except:
        return np.nan

    
def second_gender_2(f):
    try:
        g = f["SECONDARY TEAM GENDER PATHS"][1]
        return g
    except:
        return np.nan
    
def second_gender_3(f):
    try:
        g = f["SECONDARY TEAM GENDER PATHS"][2]
        return g
    except:
        return np.nan
    
def second_gender_4(f):
    try:
        g = f["SECONDARY TEAM GENDER PATHS"][3]
        return g
    except:
        return np.nan

def second_gender_5(f):
    try:
        g = f["SECONDARY TEAM GENDER PATHS"][4]
        return g
    except:
        return np.nan

def second_gender_6(f):
    try:
        g = f["SECONDARY TEAM GENDER PATHS"][5]
        return g
    except:
        return np.nan

def second_gender_7(f):
    try:
        g = f["SECONDARY TEAM GENDER PATHS"][6]
        return g
    except:
        return np.nan

def second_gender_8(f):
    try:
        g = f["SECONDARY TEAM GENDER PATHS"][7]
        return g
    except:
        return np.nan

def second_gender_9(f):
    try:
        g = f["SECONDARY TEAM GENDER PATHS"][8]
        return g
    except:
        return np.nan
    
def second_gender_10(f):
    try:
        g = f["SECONDARY TEAM GENDER PATHS_gender"][9]
        return g
    except:
        return np.nan
    

total_df["SECONDARY GENDER 01"] = total_df.apply(second_gender_1, axis=1)
total_df["SECONDARY GENDER 02"] = total_df.apply(second_gender_2, axis=1)
total_df["SECONDARY GENDER 03"] = total_df.apply(second_gender_3, axis=1)
total_df["SECONDARY GENDER 04"] = total_df.apply(second_gender_4, axis=1)
total_df["SECONDARY GENDER 05"] = total_df.apply(second_gender_5, axis=1)
total_df["SECONDARY GENDER 06"] = total_df.apply(second_gender_6, axis=1)
total_df["SECONDARY GENDER 07"] = total_df.apply(second_gender_7, axis=1)
total_df["SECONDARY GENDER 08"] = total_df.apply(second_gender_8, axis=1)
total_df["SECONDARY GENDER 09"] = total_df.apply(second_gender_9, axis=1)
total_df["SECONDARY GENDER 10"] = total_df.apply(second_gender_10, axis=1)

total_df.head(1)

,DECADE,@IMG,@TYPE_BG,TEAM LIST,DESCRIPTION,YEAR,TYPE,STATUS,TYPOLOGY_01,REM?,...,SECONDARY GENDER 01,SECONDARY GENDER 02,SECONDARY GENDER 03,SECONDARY GENDER 04,SECONDARY GENDER 05,SECONDARY GENDER 06,SECONDARY GENDER 07,SECONDARY GENDER 08,SECONDARY GENDER 09,SECONDARY GENDER 10
3,1980s,D:\Google Drive\Architecture\2017\11222 Critiq...,D:\Google Drive\Architecture\2017\11222 Critiq...,"[Kees Christiaanse, Gerard Comello, Stefano de...",Boompjes,1980,Project,Commissioned Study,Residential,True,...,D:\Google Drive\Architecture\2017\11222 Critiq...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [75]:
#Drop
total_df = total_df.drop(["DECADE", "], axis=1)

save_path = "total_output/primary-people.csv"
total_df.to_csv(save_path, index=False, encoding='utf-8')
print "Saved: " + save_path

Saved: total_output/primary-people.csv