In [2]:
# Imports
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

In [3]:
# Config matplotlib plot
%matplotlib inline
plt.rcParams['figure.figsize'] = (40, 20)
plt.rcParams['axes.titlesize'] = (30)
plt.rcParams['axes.titlepad'] = (10)
plt.rcParams['axes.labelsize'] = (20)

In [20]:
# Import data
filename = 'OMA-project-data.csv'
df = pd.read_csv(filename, dtype={'IMG_': str})

#add decade col
def create_decade(x):
    d = str(x['YEAR'])
    e = d[:3] + "0s"
    return e

df['DECADE'] = df.apply(create_decade, axis=1)

#Update image column with paths to B/W photos
bw_path = "D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Black and White Images\\"

def create_bw_path(x):
    return bw_path + str(x['IMG_']) + ".jpg"
    
df['@IMG'] = df.apply(create_bw_path, axis=1)

#Update image column with paths to Typology backgrounds
type_path = "D:\\Google Drive\\Architecture\\2017\\11222 Critique\\11222 OMA Map\\Project Data\\Typology Backgrounds\\"

def create_type_path(x):
    return type_path + str(x['TYPOLOGY_01']) + ".png"
    
df['@TYPE_BG'] = df.apply(create_type_path, axis=1)


df = df.drop(["LINK", "TYPOLOGY_02", "URL STRING", "Unnamed: 11", "IMG_", "@Photos"], axis=1)
df.head(2)

D:\Google Drive\Architecture\2017\11222 Critique\11222 OMA Map\Project Data\Black and White Images\004.jpg
D:\Google Drive\Architecture\2017\11222 Critique\11222 OMA Map\Project Data\Typology Backgrounds\Residential.png

,DESCRIPTION,YEAR,TYPE,STATUS,TYPOLOGY_01,REM?,TEAM_01,TEAM_02,TEAM_03,TEAM_04,...,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,DECADE,@IMG,@TYPE_BG
0,Delirious New York,1978,Publication,Publication,NaN,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1970s,D:\Google Drive\Architecture\2017\11222 Critiq...,D:\Google Drive\Architecture\2017\11222 Critiq...
1,Dutch Parliament Extension,1978,Project,Competition,Office,True,Zaha Hadid,Richard Perlemutter,Ron Steiner,Elias Veneris,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1970s,D:\Google Drive\Architecture\2017\11222 Critiq...,D:\Google Drive\Architecture\2017\11222 Critiq...

In [4]:
status_dict = {
               "Commissioned Study": 1,
               "Competition": 2,
               "Completed": 4,
               "Construction": 2,
               "Demolished": 2,
               "Design Development": 2,
               "Lecture": 0,
               "Publication": 4,
               "Study": 0
               }

typology_dict = {
                 "N/A": 0,
                 "Arena": 0,
                 "Branding": 1,
                 "Education": 2,
                 "Exhibition": 2,
                 "Hotel": 2,
                 "Industrial": 0,
                 "Infrastructure": 0,
                 "Landscape": 2,
                 "Library": 3,
                 "Masterplan": 3,
                 "Mixed use": 4,
                 "Museum / Gallery": 3,
                 "Office": 0,
                 "Product Design": 0,
                 "Research": 0,
                 "Residential": 1,
                 "Restaurant / Bar": 0,
                 "Retail": 2,
                 "Scenography": 3,
                 "Theatre": 3,
                 "Tower": 0
                 }

decades_dict = {
                "1970s": 5,
                "1980s": 3,
                "1990s": 1,
                "2000s": 0
                }


dict_dict = {
            "STATUS": status_dict,
            "TYPOLOGY_01": typology_dict,
            "DECADE": decades_dict
            }

In [5]:
def set_value (dictionary, key):
    max_dict = max([i for i in dictionary.values()])
    x = dictionary[key] / max_dict
    return x

def importance_factor(y):
    z = []
    
    for k in dict_dict:
        try:
            m = dict_dict[k]
            n = y[k]
            z.append(set_value(m, n))
        except:
            pass
    
    a = float(len(z))
    b = float(sum(z))
    return (b/a)

In [6]:
df['IMPORTANCE'] = df.apply(importance_factor, axis=1)

df.sort_values("IMPORTANCE", ascending=False).head(1)

,@Photos,DESCRIPTION,YEAR,TYPE,STATUS,TYPOLOGY_01,REM?,TEAM_01,TEAM_02,TEAM_03,...,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,DECADE,IMPORTANCE
0,D:\Google Drive\Architecture\2017\11222 Critiq...,Delirious New York,1978,Publication,Publication,NaN,True,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1970s,1.0

In [7]:
# Organise columns
df["TEAM LIST"] = np.nan

cols = df.columns.tolist()
cols = cols[-3:] + cols[:-3]
df = df[cols]
df.head(5)

,DECADE,IMPORTANCE,TEAM LIST,@Photos,DESCRIPTION,YEAR,TYPE,STATUS,TYPOLOGY_01,REM?,...,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109
0,1970s,1.000000,NaN,D:\Google Drive\Architecture\2017\11222 Critiq...,Delirious New York,1978,Publication,Publication,NaN,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1970s,0.333333,NaN,D:\Google Drive\Architecture\2017\11222 Critiq...,Dutch Parliament Extension,1978,Project,Competition,Office,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1970s,0.333333,NaN,D:\Google Drive\Architecture\2017\11222 Critiq...,Irish Prime Minister's Residence,1979,Project,Competition,Office,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1980s,0.000000,NaN,D:\Google Drive\Architecture\2017\11222 Critiq...,Boompjes,1980,Project,Commissioned Study,Residential,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1980s,0.000000,NaN,D:\Google Drive\Architecture\2017\11222 Critiq...,Kochstrasse / Friedrichstrasse Housing,1980,Project,Competition,Residential,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
team_cols = df.loc[:, 'TEAM_01':].columns.tolist()
team_cols_len = len(team_cols)

def create_team(x):
    y = []
    for i in team_cols:
        y.append(x[i])
    return y

df["TEAM LIST"] = df.apply(create_team, axis=1)

df.head(2)

,DECADE,IMPORTANCE,TEAM LIST,@Photos,DESCRIPTION,YEAR,TYPE,STATUS,TYPOLOGY_01,REM?,...,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109
0,1970s,1.000000,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",D:\Google Drive\Architecture\2017\11222 Critiq...,Delirious New York,1978,Publication,Publication,NaN,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1970s,0.333333,"[Zaha Hadid, Richard Perlemutter, Ron Steiner,...",D:\Google Drive\Architecture\2017\11222 Critiq...,Dutch Parliament Extension,1978,Project,Competition,Office,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
team_list = df["TEAM LIST"].tolist()

def find_names(name):
    j = []

    for i in team_list:
        j.append(name in i)
    return j

def name_frame(name):
    p = find_names(name)
    q = df[p]
    return q

In [10]:
# Load name list
name_file = 'key-people-list.txt'
file_open = open(name_file)
c = file_open.readlines()
name_list = []
for i in c:
    y = i.strip()
    name_list.append(y)
    
print name_list

['Generation-01_Christian Rapp', 'Generation-01_Edzo Bindels', 'Generation-01_Christophe Cornubert', 'Generation-01_Matthias Sauerbruch', 'Generation-01_Kees Christiaanse', 'Generation-01_Yushi Uehara', 'Generation-01_Zaha Hadid', 'Generation-01_Laurinda Spear', 'Generation-01_Ruurd Roorda', 'Generation-01_Williem Jan Neutelings', 'Generation-01_Winy Maas', 'Generation-01_Jacob Van Rijs', 'Generation-01_Sarah Whiting', 'Generation-01_Ron Witte', 'Generation-01_Mike Guyer', 'Generation-01_Alejandro Zaera Polo', 'Generation-01_Luc Reuse', 'Generation-01_Farshid Moussavi', 'Generation-01_Rients Dijkstra', 'Generation-02_Jeffery Inaba', 'Generation-02_Xaveer de Geyter', 'Generation-02_Amale Andraos', 'Generation-02_Dan Wood', 'Generation-02_Juliette Bekkering', 'Generation-02_John Mcmorrough', 'Generation-02_Matthias Hollwich', 'Generation-02_Jeanne Gang', 'Generation-02_Fernando Romero', 'Generation-02_Markus Schaefer', 'Generation-02_Zachary R.Heineman', 'Generation-02_Joshua Prince-Ramus', 'Generation-02_Erez Ella', 'Generation-02_Bjarke Ingels', 'Generation-02_Julien De Smedt', 'Generation-02_Patrick Louwere', 'Generation-02_Bart Eijking', 'Generation-02_Ole Scheeren', 'Generation-02_Eric Chang', 'Projects-01_Jeroen Thomas', 'Projects-02_Ron Steiner', 'Projects-03_Chris van Duijn', 'Projects-04_Frans Blok', 'Projects-05_Shohei Shigematsu', 'Projects-06_Reinier de Graaf', 'Projects-07_Xaveer de Geyter', 'Projects-08_Floris Alkemade', 'Projects-09_Fernando Donis', 'Projects-10_Dan Wood']

In [11]:
def process_names(d):
    e = d.split('_')
    f = name_frame(e[1])
    h = len(f["YEAR"].tolist())
    f["BRANCH KEY"] = e[1]
    f["KEY LIST"] = e[0]
    f["KEY TOTAL"] = h
    print "Done: " + d
    return f

count = 0
index = []
columns = []
total_df = pd.DataFrame(index=index, columns=columns)

for g in name_list:
    total_df = total_df.append(process_names(g))
    count += 1
    
save_path = "people_output/_total-people.csv"
total_df.to_csv(save_path, index=False)
print "Processed: " + str(count)

/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

Done: Generation-01_Christian Rapp
Done: Generation-01_Edzo Bindels
Done: Generation-01_Christophe Cornubert
Done: Generation-01_Matthias Sauerbruch
Done: Generation-01_Kees Christiaanse
Done: Generation-01_Yushi Uehara
Done: Generation-01_Zaha Hadid
Done: Generation-01_Laurinda Spear
Done: Generation-01_Ruurd Roorda
Done: Generation-01_Williem Jan Neutelings
Done: Generation-01_Winy Maas
Done: Generation-01_Jacob Van Rijs
Done: Generation-01_Sarah Whiting
Done: Generation-01_Ron Witte
Done: Generation-01_Mike Guyer
Done: Generation-01_Alejandro Zaera Polo
Done: Generation-01_Luc Reuse
Done: Generation-01_Farshid Moussavi
Done: Generation-01_Rients Dijkstra
Done: Generation-02_Jeffery Inaba
Done: Generation-02_Xaveer de Geyter
Done: Generation-02_Amale Andraos
Done: Generation-02_Dan Wood
Done: Generation-02_Juliette Bekkering
Done: Generation-02_John Mcmorrough
Done: Generation-02_Matthias Hollwich
Done: Generation-02_Jeanne Gang
Done: Generation-02_Fernando Romero
Done: Generation-02_Markus Schaefer
Done: Generation-02_Zachary R.Heineman
Done: Generation-02_Joshua Prince-Ramus
Done: Generation-02_Erez Ella
Done: Generation-02_Bjarke Ingels
Done: Generation-02_Julien De Smedt
Done: Generation-02_Patrick Louwere
Done: Generation-02_Bart Eijking
Done: Generation-02_Ole Scheeren
Done: Generation-02_Eric Chang
Done: Projects-01_Jeroen Thomas
Done: Projects-02_Ron Steiner
Done: Projects-03_Chris van Duijn
Done: Projects-04_Frans Blok
Done: Projects-05_Shohei Shigematsu
Done: Projects-06_Reinier de Graaf
Done: Projects-07_Xaveer de Geyter
Done: Projects-08_Floris Alkemade
Done: Projects-09_Fernando Donis
Done: Projects-10_Dan Wood
Processed: 48